export const dashboard = <i className="fa-solid fa-house-user"></i>
export const transactions = <i className="fa-regular fa-credit-card"></i>
export const categories = <i className="fa-solid fa-list"></i>
export const accounts = <i className="fa-solid fa-wallet"></i>
export const settings = <i className="fa-solid fa-cog"></i>
export const logout = <i className="fa-solid fa-sign-out-alt"></i>
export const trend = <i className="fa-solid fa-chart-line"></i>
export const expense = <i className="fa-solid fa-money-bill-wave"></i>
export const money = <i className="fa-solid fa-dollar-sign"></i>
export const freelance = <i className="fa-solid fa-laptop-code"></i>
export const stocks = <i className="fa-solid fa-chart-bar"></i>
export const crypto = <i className="fa-solid fa-coins"></i>
export const savings = <i className="fa-solid fa-piggy-bank"></i>
export const yt = <i className="fa-brands fa-youtube"></i>
export const card = <i className="fa-regular fa-credit-card"></i>
export const users = <i className="fa-solid fa-users"></i>
export const dollar = <i className="fa-solid fa-dollar-sign"></i>
export const calendar = <i className="fa-regular fa-calendar-alt"></i>
export const comment = <i className="fa-regular fa-comment"></i>
export const plus = <i className="fa-solid fa-plus"></i>
export const trash = <i className="fa-solid fa-trash-alt"></i>
export const signout = <i className="fa-solid fa-sign-out-alt"></i>
export const takeaway = <i className="fa-solid fa-utensils"></i>
export const clothing = <i className="fa-solid fa-tshirt"></i>
export const book = <i className="fa-solid fa-book"></i>
export const food = <i className="fa-solid fa-hamburger"></i>
export const medical = <i className="fa-solid fa-medkit"></i>
export const tv = <i className="fa-solid fa-tv"></i>
export const circle = <i className="fa-solid fa-circle"></i>
